### GET request to example server
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "id": "223e4567-e89b-12d3-a456-426614174014",
  "name": "jake1",
  "email": "jake@jakemail.com",
  "address": "jakepuram jake street1",
  "dateOfBirth": "1995-02-12",
  "registeredDate": "2025-10-25"
}
###